# Generated by Django 4.2.5 on 2024-04-02 20:08

from decimal import Decimal

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_clean_prediction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость тарифного плана в рублях')),
                ('price_ton', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость тарифного плана в TON')),
                ('price_usdt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость тарифного плана в USDT')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение тарифного плана')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ тарифного плана')),
                ('title', models.CharField(max_length=255, verbose_name='Название тарифного плана')),
                ('text', models.TextField(blank=True, verbose_name='Описание тарифного плана')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='Период действия тарифного плана в днях')),
                ('number_of_actions', models.IntegerField(blank=True, null=True, verbose_name='Количество доступных действий')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальный тарифный план или нет')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифный план',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('amount_rub', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Количество рублей')),
                ('amount_ton', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Количество ton')),
                ('amount_usdt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Количество usdt')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='telegram_clean_prediction.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Кошелек пользователя',
                'verbose_name_plural': 'Кошельки пользователей',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('expired_at', models.DateTimeField(auto_now=True, verbose_name='Срок действия подписки')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='telegram_clean_prediction.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('success', 'Успех'), ('error', 'Ошибка')], verbose_name='Статус платежа')),
                ('currency', models.CharField(choices=[('rub', 'Рубль'), ('ton', 'Toncoin'), ('usdt', 'Usdt')], verbose_name='Валюта платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество внесенных денежных средств')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='telegram_clean_prediction.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Платеж клиента',
                'verbose_name_plural': 'Платежи клиентов',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
